package com.erms.model;

public class Employee {
    // Encapsulation: Private fields
    private int id;
    private String firstName;
    private String lastName;
    private String email;
    private String position;
    private double salary;

    // Constructors
    public Employee() {
    }

    // Constructor for creating a new employee (ID is auto-generated by DB)
    public Employee(String firstName, String lastName, String email, String position, double salary) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.position = position;
        this.salary = salary;
    }

    // Constructor for updating/reading an existing employee
    public Employee(int id, String firstName, String lastName, String email, String position, double salary) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.position = position;
        this.salary = salary;
    }

    // Getters and Setters (Encapsulation)
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPosition() { return position; }
    public void setPosition(String position) { this.position = position; }

    public double getSalary() { return salary; }
    public void setSalary(double salary) { this.salary = salary; }
}